### ISSUE TITLE
RemotePushDelegate.h file not found

### ISSUE THREAD

**Issue by lazaronixon** [darylrowland/react-native-remote-push#1]
I tried to use react-native-remote-push but any callback is triggered, so on docs i see that is necessary put  #import "RemotePushDelegate.h" to AppDelegate.m. but i get a file not found alert on xcode.

**Comment by darylrowland** [comment]
Have you added the .m and .h files from the repo to your XCode project? Sounds like that might be the problem, if XCode isn't finding them in your build path

**Comment by darylrowland** [comment]
Massive apologies! My mistake, I hadn't checked in the file. It's now been pushed to the repository.
