### ISSUE TITLE
Causes peer dependency errors when installing

### ISSUE THREAD

**Issue by isair** [darylrowland/react-native-remote-push#10]
Happens when using react-native 0.7.x and 0.8.0. Didn't test for earlier versions.

Doesn't happen if I add it to my package.json as:

```
"react-native-remote-push": "git://github.com/darylrowland/react-native-remote-push.git#ce209f4"
```

And doing an `npm install` instead of doing `npm install react-native-remote-push --save`. So pushing the latest state of master to npm will fix this.

**Comment by darylrowland** [comment]
I've published the current master now, so hopefully this should be fixed!
