### ISSUE TITLE
Difference with PushNotificationIOS

### ISSUE THREAD

**Issue by ericvicenti** [darylrowland/react-native-remote-push#5]
What does this module offer that isn't provided by [PushNotificationIOS](http://facebook.github.io/react-native/docs/pushnotificationios.html#content)? In the documentation, could you explain the reasoning behind the separate module?

We would be happy to review any pull requests you want to offer for PushNotificationIOS in React Native

**Comment by frenchie4111** [comment]
As far as I can tell PushNotificationIOS does not have the ability to register for remote notifications, and receive a device token to send to the server

**Comment by darylrowland** [comment]
Yeah that's basically it @frenchie4111 - I struggled to get the React Native PushNotificationIOS receiving remote notifications and registering for a device token.

In the end some changes needed to be made to the AppDelegate, and I didn't think these really belonged in the Push Notification lib bundled with React Native - but, when I get a few more moments I'll see if there is a nicer way of doing this and create a pull request.

**Comment by ericvicenti** [comment]
Thanks! It would be great if we could remove the duplication and have one lib that works for everything

I'll close this for now, but it would be great if the differences were more clearly documented. And of course it would be great to get the remote token functionality in PushNotificationIOS!

**Comment by Ouadie** [comment]
**react-native** implements this behavior by default now, so is **react-native-remote-push** deprecated?
