### ISSUE TITLE
[Feature] Distinguish between PN's received while app open vs PN's clicked through to app.

### ISSUE THREAD

**Issue by MossP** [darylrowland/react-native-remote-push#7]
Now that I have it working, this seems a great plugin but I've noticed the info passed back to React-Native doesn't distinguish between Push Notifications that were received while the app is open versus those that were clicked from the lock screen. Am I missing something?

**Comment by darylrowland** [comment]
You're right, at the moment it doesn't distinguish between these. I think it would be pretty easy to add a flag for this though if its something you're interested in creating a pull request for?

**Comment by MossP** [comment]
Yeah, I'll have a look at it over the next week [read - learn Objective C and how to do pull requests :) ]

Thanks for the reply and for the plugin :) :+1:
