### ISSUE TITLE
No notification event ever gets called.

### ISSUE THREAD

**Issue by timminkov** [darylrowland/react-native-remote-push#8]
Using React 0.5 - 

``` javascript
DeviceEventEmitter.addListener(
  REGISTERED_FOR_REMOTE, function(notification) {
    console.log('literally anything');
    callback(null, notification);
  }
);

DeviceEventEmitter.addListener(
  REGISTERED_FOR_REMOTE_ERROR, function(error) {
    console.log('literally anything');
    callback("Couldn't register for notifications");
  }
)
```

and calling 

``` javascript
RemotePushIOS.requestPermissions(function(err, data) {});
```

I get nothing, both in simulator and on-phone after pressing the "allow" button. I've followed the steps to get it set up (including adding `#import "RemotePushDelegate.h"` to my AppDelegate.m). I installed via NPM and dragged the project file into my library. 

No matter what, I cannot get an a token back. Any ideas?

**Comment by frenchie4111** [comment]
You should be receiving the token in the requestPermissions callback

```
RemotePushIOS.requestPermissions( function( err, data ) {
    if( err ) {
        console.error( 'We fucked up:', err );
    } else {
        console.log( data.token );
    }
} );
```

**Comment by timminkov** [comment]
No event ever gets triggered - I added logging in the actual addlistener functions above.

**Comment by jawadrehman** [comment]
I have the same issue as well .

**Comment by MossP** [comment]
Even though you installed via npm, still follow the steps of adding each of the required files not just the one mentioned to include see https://github.com/darylrowland/react-native-remote-push/issues/2

**Comment by ohadperry** [comment]
this helped me
https://github.com/facebook/react-native/issues/1613

**Comment by darylrowland** [comment]
Looks like this is resolved, so I'm closing now
